version: "3.7"

networks:
  shared:
    driver: bridge

services:
  docker-host:
    image: qoomon/docker-host
    container_name: docker-host
    restart: on-failure
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      - shared

  openresty:
    build: .
    container_name: nginx
    restart: on-failure
    volumes:
      - ./docker/nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/ffdhe2048.txt:/etc/nginx/ffdhe2048.txt:ro
      - ./docker/resty-auto-ssl/dehydrated.sh:/etc/resty-auto-ssl/letsencrypt/conf.d/dehydrated.sh:ro
      - ./docker/resty-auto-ssl/hooks/cloudfront.sh:/etc/resty-auto-ssl/hooks/cloudfront.sh:ro
      - ./public:/etc/nginx/html/client:ro
      - ./docker/data/nginx/cache:/data/nginx/cache
      - ./docker/data/resty-auto-ssl:/etc/resty-auto-ssl
      - /home/user/.sia/apipassword:/etc/.sia/apipassword:ro
    networks:
      - shared
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - docker-host
  # server:
  #   build:
  #     context: .
  #     dockerfile: docker/server/Dockerfile
  #   working_dir: /usr/src
  #   entrypoint: ["node", "server/index.js"]
  #   container_name: server
  #   restart: on-failure
  #   volumes:
  #     - ./server:/usr/src/server
  #     - ./package.json:/usr/src/package.json
  #     - ./yarn.lock:/usr/src/yarn.lock
  #   env_file: .env
  #   expose:
  #     - 8080
  #   depends_on:
  #     - mongo
  #   networks:
  #     - shared
  # mongo-express:
  #   image: mongo-express
  #   container_name: admin
  #   restart: on-failure
  #   expose:
  #     - 8081
  #   networks:
  #     - shared
  #   depends_on:
  #     - mongo
  #   env_file: .env
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
  # mongo:
  #   image: mongo
  #   container_name: mongo
  #   restart: on-failure
  #   volumes:
  #     - ./docker/data/db:/data/db
  #   expose:
  #     - 27017
  #   networks:
  #     - shared
  #   env_file: .env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
